package Tela;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class Cadastro extends javax.swing.JFrame {

    private boolean senhaVisivel = false; // Estado inicial da senha oculta

    public Cadastro() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void toggleSenhaVisibilidade() {
        senhaVisivel = !senhaVisivel;
        senhaJtx.setEchoChar(senhaVisivel ? '\0' : '*');
        toggleSenhaBtn.setText(senhaVisivel ? "Ocultar" : "Mostrar");
    }

    private static boolean cadastrar(String usuario, String nome, String email, String senha) {
        try (Connection conn = Database.getConnection(); PreparedStatement stmt = conn.prepareStatement("INSERT INTO cadastro(usuario, nome, email, senha) VALUES (?, ?, ?, ?)")) {
            stmt.setString(1, usuario);
            stmt.setString(2, nome);
            stmt.setString(3, email);
            stmt.setString(4, senha);
            stmt.executeUpdate();
            return true;
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar: " + ex.getMessage());
            return false;
        }
    }

    private boolean verificarCamposPreenchidos(String usuario, String nome, String email, String senha) {
        return !usuario.isEmpty() && !nome.isEmpty() && !email.isEmpty() && !senha.isEmpty();
    }

    private boolean validarEmail(String email) {
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        if (!Pattern.compile(emailRegex).matcher(email).matches()) {
            JOptionPane.showMessageDialog(this, "Formato de email inválido. Use o formato: exemplo@dominio.com");
            return false;
        }
        return true;
    }

    private boolean validarSenha(String senha) {
        if (senha.length() < 8 || !Pattern.compile("[A-Za-z]").matcher(senha).find()
                || !Pattern.compile("[0-9]").matcher(senha).find()) {
            JOptionPane.showMessageDialog(this, "A senha deve ter pelo menos 8 caracteres, com letras e números.");
            return false;
        }
        return true;
    }

    private void entreLogActionPerformed() {
        JFrame loginFrame = new Login();
        loginFrame.setVisible(true);
        loginFrame.setLocationRelativeTo(null);
    }

    public static void main(String args[]) {
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(() -> new Cadastro().setVisible(true));
        // Variáveis de declaração
    }
    private javax.swing.JButton cadastrarBtn;
    private javax.swing.JTextField emailJtx;
    private javax.swing.JButton entreLog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JTextField nomeJtx;
    private javax.swing.JPasswordField senhaJtx; // Campo de senha oculto por padrão
    private javax.swing.JTextField usuarioJtx;
    private javax.swing.JButton toggleSenhaBtn; // Botão para alternar visibilidade da senha

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
